### ISSUE TITLE
A lot of items scenario?

### ISSUE THREAD

**Issue by bernaferrari** [faob-dev/MotionLayoutCarousel#1]
Hi, I'm currently using [DiscreteScrollView](https://github.com/yarolegovich/DiscreteScrollView) for my layouts. Your implementation with Motion Layout is really interesting, and could even be used [by me](https://github.com/bernaferrari/CarouselGifViewer). However, I can't understand if it can be expanded to hundreds of elements or that is it. Any comments?

**Comment by faob-dev** [comment]
hi brother Its just hello world example to show motionlayout usage. For big items you can embed motionlayout in  **DiscreteScrollView** or **ViewPager** and you can run animation from java code each page will have its own motionlayout. 
I did exact thing in one of my demos https://twitter.com/faaoob/status/1058099167808118784
Each item in recyclerview has its own motionlayout and i can run animation based on click.
