### ISSUE TITLE
How to know that layout transaction is completed?

### ISSUE THREAD

**Issue by Dnyaneshwar1926** [faob-dev/MotionLayoutCarousel#2]
Whenever a transaction is ended. I want to display a toast message that the layout is collapsed/Expanded. How to achieve this?

**Comment by faob-dev** [comment]
To handle layout transition end add `setTransitionListener` and handle `onTransitionCompleted`

```kotlin
val motionLayout = findViewById<MotionLayout>(R.id.motion_container)
motionLayout.setTransitionListener(object : MotionLayout.TransitionListener{
    override fun onTransitionCompleted(motionLayout: MotionLayout?, currentId: Int) {
        if(currentId == R.id.s1){
            println("On Blue View")
        }else if(currentId == R.id.s2){
            println("On Orange View")
        }else if(currentId == R.id.s3){
            println("On Red View")
        }
    }
})
```

**Comment by Dnyaneshwar1926** [comment]
> To handle layout transition end add `setTransitionListener` and handle `onTransitionCompleted`
> 
> ```kotlin
> val motionLayout = findViewById<MotionLayout>(R.id.motion_container)
> motionLayout.setTransitionListener(object : MotionLayout.TransitionListener{
>     override fun onTransitionCompleted(motionLayout: MotionLayout?, currentId: Int) {
>         if(currentId == R.id.s1){
>             println("On Blue View")
>         }else if(currentId == R.id.s2){
>             println("On Orange View")
>         }else if(currentId == R.id.s3){
>             println("On Red View")
>         }
>     }
> })
> ```

Thank you :)
